# Error Handling Async & Await

You are going to continue with the previous exercise and add error handling. If there is some kind of error, like a network timeout for example, use `try ... catch` to display an error message onto the screen. You can fake a network outage by temporarily changing the URL to something that does not exist.
